library(icash)
options(shiny.maxRequestSize=500*1024^2)
raw_fd <- system.file('extdata', 'rawdata', package="icash")
filenames<-list.files(path=raw_fd)
# filenames<-list.files(path="./extdata", pattern="\\.txt$")
geneset_fd <- system.file("extdata", "geneset", package="icash")
genefile_fd <- system.file("extdata", "genefile", package="icash")
pre_geneset <- load_geneset(geneset_fd, ".gmt")
pre_genelist <- load_genelist(genefile_fd, ".txt")
`%then%` <- shiny:::`%OR%`
